<?php

namespace AppBundle\Repository;

/**
 * ContributorRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContributorRepository extends \Doctrine\ORM\EntityRepository
{
    public function findFromIdentifier($type, $identifer)
    {
        return $this->getEntityManager()
        ->createQuery(
            'SELECT c
            FROM AppBundle:Contributor c
            JOIN c.identifiers i
            JOIN i.identifierType it
            WHERE i.identifier = :identifier
            AND it.name = :type')
        ->setParameter('identifier', $identifer)
        ->setParameter('type', $type)
        ->getSingleResult();
    }
}
