<?php

namespace AppBundle\Repository;

/**
 * IdentifierRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdentifierRepository extends \Doctrine\ORM\EntityRepository
{
}
