<?php

namespace AppBundle\Repository;

/**
 * IdentifierTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IdentifierTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
