parameters:
    source.civiweb.base_uri: https://civicrm.org/api/ 
    source.civicrm.base_uri: https://civicrm.org/sites/all/modules/civicrm/extern/rest.php
    source.stack_exchange.base_uri: https://api.stackexchange.com/2.2/

services:

    poll:
        abstract: true
        calls:
            - ["init"]
    source:
        abstract: true
        calls:
            - ["init"]

# Polls
# Tip: A poll should define it's parent as poll

    poll.commits:
        parent: poll
        class: AppBundle\Utils\Poll\Commits
        arguments: ['@source.github']

    poll.nodes:
        parent: poll
        class: AppBundle\Utils\Poll\Nodes
        arguments: ['@source.civiweb']
    
    poll.extensions:
        parent: poll
        class: AppBundle\Utils\Poll\Extensions
        arguments: ['@source.civiweb']

    poll.extension_releases:
        parent: poll
        class: AppBundle\Utils\Poll\ExtensionReleases
        arguments: ['@source.civiweb']
    
    poll.comments:
        parent: poll
        class: AppBundle\Utils\Poll\Comments
        arguments: ['@source.civiweb']
    
# Sources
# Tip: A source should define it's parent as source

    source.civiweb:
        parent: source
        class: AppBundle\Utils\Source\CiviWeb
        arguments: ['%source.civiweb.base_uri%']
        
    source.civicrm:
        parent: source
        class: AppBundle\Utils\Source\CiviCRM
        arguments: ['%source.civicrm.base_uri%', '%source.civicrm.key%', '%source.civicrm.api_key%']
        
    source.github:
        parent: source
        class: AppBundle\Utils\Source\Github
        arguments: ['@github.client', '@github.result_pager', '%source.github.auth_http_token%']

    github.result_pager:
        class: Github\ResultPager
        arguments: ['@github.client']

    github.client:
        class: Github\Client
        arguments: ['@github.cached_http_client']

    github.cached_http_client:
        class: Github\HttpClient\CachedHttpClient
        arguments:
            - cache_dir: "%kernel.cache_dir%/github-api-cache"
            
